#!/usr/bin/env python3
"""Generate INDEX.md from the live repo tree + scripts/index_annotations.json."""

import json
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
ANNOTATIONS_FILE = Path(__file__).parent / "index_annotations.json"
OUTPUT_FILE = REPO_ROOT / "INDEX.md"

TODO = "# TODO: add annotation"


def load_annotations():
    with open(ANNOTATIONS_FILE) as f:
        return json.load(f)


def collect_paths(config):
    exclude = set(config.get("exclude", []))
    expand = set(config.get("expand", []))
    paths = {}

    for entry in sorted(REPO_ROOT.iterdir()):
        name = entry.name
        if name in exclude:
            continue
        rel = name
        paths[rel] = entry.is_dir()

        if entry.is_dir() and name in expand:
            for sub in sorted(entry.iterdir()):
                if sub.name.startswith("__") or sub.name in exclude:
                    continue
                rel2 = f"{name}/{sub.name}"
                paths[rel2] = sub.is_dir()

    return paths


def render(config, fs_paths):
    annotations = config["paths"]
    groups_order = [g[0] for g in config["groups"]]
    groups_display = {g[0]: g[1] for g in config["groups"]}

    # Bucket paths into groups; track unannotated
    buckets = {g: [] for g in groups_order}
    unannotated = []

    for rel in sorted(fs_paths):
        if rel in annotations:
            entry = annotations[rel]
            group = entry.get("group", "dev")
            desc = entry.get("description", TODO)
            buckets.setdefault(group, []).append((rel, desc, fs_paths[rel]))
        else:
            unannotated.append(rel)

    lines = [
        "# Willow 2.0 — File Index",
        "",
        f"> Auto-generated by `scripts/gen_index.py` on {date.today()}. "
        "Add or update descriptions in `scripts/index_annotations.json`.",
        "",
    ]

    for group_key in groups_order:
        entries = buckets.get(group_key, [])
        if not entries:
            continue
        lines.append(f"## {groups_display[group_key]}")
        lines.append("")
        lines.append("| Path | Description |")
        lines.append("|------|-------------|")
        for rel, desc, is_dir in entries:
            display = f"`{rel}/`" if is_dir else f"`{rel}`"
            lines.append(f"| {display} | {desc} |")
        lines.append("")

    if unannotated:
        lines.append("## Unannotated (add to index_annotations.json)")
        lines.append("")
        lines.append("| Path |")
        lines.append("|------|")
        for rel in unannotated:
            lines.append(f"| `{rel}` |")
        lines.append("")

    return "\n".join(lines)


def main():
    config = load_annotations()
    fs_paths = collect_paths(config)
    output = render(config, fs_paths)
    OUTPUT_FILE.write_text(output)
    print(f"wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
